---
# note: current-user is a dependency, but it won't run
# if you use a tag to select just the setup tasks
- name: Get info on current user
  include_role: 
    name: marvel-nccr.current-user
  when: current_user is undefined

- name: create ipython config folder
  file:
    path: "${HOME}/.ipython/profile_default"
    state: directory

- name: setup AiiDA jupyter extension
  copy:
    src: ipython_config.py
    dest: "${HOME}/.ipython/profile_default"

- name: create aiidalab folders
  become: True
  become_user: "{{ root_user }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ current_user }}"
  with_items:
    - "{{ aiidalab_base_folder }}"
    - "{{ aiidalab_apps_folder }}"

- name: add __init__.py for import
  copy:
    src: __init__.py
    dest: "{{ aiidalab_apps_folder }}"

- name: add launcher script
  template:
    src: start.sh
    dest: "{{ aiidalab_apps_folder }}"
    mode: 0753

- name: update PYTHONPATH
  lineinfile:
    path: "${HOME}/.profile"
    line: 'export PYTHONPATH=$PYTHONPATH:{{ aiidalab_base_folder }}'

- name: create aiidalab apps symlink
  file:
    src: "{{ aiidalab_apps_folder }}"
    dest: "{{ aiidalab_apps_symlink }}"
    state: link

- name: desktop icon
  block:
  - name: make icons directory
    file:
      dest: "${HOME}/.icons"
      state: directory
  
  - name: copy aiida icon
    copy:
      src: aiidalab_gears_square_256.png
      dest: "${HOME}/.icons/"
  
  - name: create desktop shortcut
    template:
      src: apps.desktop
      dest: "${HOME}/Desktop"
      mode: 0753
  when: not aiidalab_headless

# below: stuff needed for jupyterhub
#- name: copy singleuser script
#  copy:
#    src: mc-jupyter-singleuser
#    dest: "{{ aiidalab_venv }}/bin"
#    mode: u+x

#- name: start jupyter notebook server
#  shell: |
#    {{ aiidalab_venv }}/bin/mc-jupyterhub-singleuser \
#    --ip=0.0.0.0  \
#    --port=8888   \
#    --notebook-dir="{{ aiidalab_apps_folder }}" \
#    --NotebookApp.iopub_data_rate_limit=1000000000 \
#    --NotebookApp.default_url="/apps/home/start.ipynb"
